// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimvestFun.Infrastructure;

#nullable disable

namespace SimvestFun.Infrastructure.Migrations
{
    [DbContext(typeof(SimvestFunContext))]
    [Migration("20220311153540_InitialStockDataFixed")]
    partial class InitialStockDataFixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimvestFun.ApplicationCore.Entities.Stock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = "AAPL",
                            CurrentPrice = 162.94999999999999,
                            Index = 1,
                            Industry = "Consumer electronics, software and online services",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = "MSFT",
                            CurrentPrice = 288.5,
                            Index = 2,
                            Industry = "Multinational technology",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = "GOOG",
                            CurrentPrice = 2677.0,
                            Index = 3,
                            Industry = "Conglomerate",
                            Name = "Alphabet"
                        },
                        new
                        {
                            Id = "AMZN",
                            CurrentPrice = 2786.0,
                            Index = 4,
                            Industry = "E-commerce",
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = "TSLA",
                            CurrentPrice = 858.97000000000003,
                            Index = 5,
                            Industry = "Electric vehicle and clean energy",
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = "BRK.B",
                            CurrentPrice = 488245.0,
                            Index = 6,
                            Industry = "Financial services",
                            Name = "Berkshire Hathaway"
                        },
                        new
                        {
                            Id = "NVDA",
                            CurrentPrice = 230.13999999999999,
                            Index = 7,
                            Industry = "Visual computing",
                            Name = "Nvidia"
                        },
                        new
                        {
                            Id = "FB",
                            CurrentPrice = 198.5,
                            Index = 8,
                            Industry = "Information technology",
                            Name = "Meta"
                        },
                        new
                        {
                            Id = "UNH",
                            CurrentPrice = 485.56999999999999,
                            Index = 9,
                            Industry = "Managed healthcare insurance",
                            Name = "United Health"
                        },
                        new
                        {
                            Id = "JNJ",
                            CurrentPrice = 169.36000000000001,
                            Index = 10,
                            Industry = "Pharmaceutical Medical devices Consumer healthcare",
                            Name = "Johnson & Johnson"
                        },
                        new
                        {
                            Id = "V",
                            CurrentPrice = 199.75999999999999,
                            Index = 11,
                            Industry = "Financial services",
                            Name = "Visa"
                        },
                        new
                        {
                            Id = "JPM",
                            CurrentPrice = 133.44,
                            Index = 12,
                            Industry = "Financial services",
                            Name = "JPMorgan Chase"
                        },
                        new
                        {
                            Id = "WMT",
                            CurrentPrice = 139.46000000000001,
                            Index = 13,
                            Industry = "Retail",
                            Name = "Walmart"
                        },
                        new
                        {
                            Id = "PG",
                            CurrentPrice = 148.77000000000001,
                            Index = 14,
                            Industry = "Consumer goods",
                            Name = "Procter & Gamble"
                        },
                        new
                        {
                            Id = "XOM",
                            CurrentPrice = 82.790000000000006,
                            Index = 15,
                            Industry = "Oil and gas",
                            Name = "Exxon Mobil"
                        },
                        new
                        {
                            Id = "HD",
                            CurrentPrice = 317.19999999999999,
                            Index = 16,
                            Industry = "Retail",
                            Name = "Home Depot"
                        },
                        new
                        {
                            Id = "BAC",
                            CurrentPrice = 41.039999999999999,
                            Index = 17,
                            Industry = "Financial services",
                            Name = "Bank of America"
                        },
                        new
                        {
                            Id = "CVX",
                            CurrentPrice = 166.27000000000001,
                            Index = 18,
                            Industry = "Oil and gas",
                            Name = "Chevron"
                        },
                        new
                        {
                            Id = "MA",
                            CurrentPrice = 328.13,
                            Index = 19,
                            Industry = "Payments",
                            Name = "Mastercard"
                        },
                        new
                        {
                            Id = "PFE",
                            CurrentPrice = 48.75,
                            Index = 20,
                            Industry = "Pharmaceutical and biotechnology",
                            Name = "Pfizer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
